version: '3'
services:
    app: 
        build: .
        volumes: 
            - .:/app
        ports: 
            - 9000:3000
        environment:
            HOST: https://s.a-chacon.com
            RAILS_ENV: production
            SECRET_KEY: "0xBBb166E8989a9070013A8f3f26504893586D45C2"
            VERIFY_URL: https://hcaptcha.com/siteverify
            RAILS_LOG_TO_STDOUT: true
            RAILS_SERVE_STATIC_FILES: true

