# fly.toml app configuration file generated for paso on 2023-10-07T17:06:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "paso"
primary_region = "scl"
console_command = "/rails/bin/rails console"

[build]

[[mounts]]
source = "data"
destination = "/data"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[statics]]
guest_path = "/rails/public"
url_prefix = "/"
